/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Victor Pino
 */

public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProyectos = new javax.swing.JMenu();
        mnuProyectoRegistrar = new javax.swing.JMenuItem();
        mnuProyectoUpDele = new javax.swing.JMenuItem();
        mnuPersonal = new javax.swing.JMenu();
        mnuPersonalGestion = new javax.swing.JMenuItem();
        mnuRecibos = new javax.swing.JMenu();
        mnuRecibosRegistrar = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja Chica");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        mnuProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Archivo.png"))); // NOI18N
        mnuProyectos.setText("Gestion de Proyectos");

        mnuProyectoRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        mnuProyectoRegistrar.setText("Registrar");
        mnuProyectoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProyectoRegistrarActionPerformed(evt);
            }
        });
        mnuProyectos.add(mnuProyectoRegistrar);

        mnuProyectoUpDele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update-32.png"))); // NOI18N
        mnuProyectoUpDele.setText("Modificar y/o Eliminar");
        mnuProyectoUpDele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProyectoUpDeleActionPerformed(evt);
            }
        });
        mnuProyectos.add(mnuProyectoUpDele);

        jMenuBar1.add(mnuProyectos);

        mnuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuarios.png"))); // NOI18N
        mnuPersonal.setText("Personal");

        mnuPersonalGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gestion-32.png"))); // NOI18N
        mnuPersonalGestion.setText("Gestion");
        mnuPersonalGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPersonalGestionActionPerformed(evt);
            }
        });
        mnuPersonal.add(mnuPersonalGestion);

        jMenuBar1.add(mnuPersonal);

        mnuRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        mnuRecibos.setText("Gestion de Recibos");

        mnuRecibosRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Factura.png"))); // NOI18N
        mnuRecibosRegistrar.setText("Registrar");
        mnuRecibosRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRecibosRegistrarActionPerformed(evt);
            }
        });
        mnuRecibos.add(mnuRecibosRegistrar);

        jMenuBar1.add(mnuRecibos);

        mnuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        mnuConsultas.setText("Consultas");
        jMenuBar1.add(mnuConsultas);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        mnuSalir.setText("Salir");
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRecibosRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRecibosRegistrarActionPerformed
       
        frmFactura fac = new frmFactura();
        fac.setVisible(true);
        fac.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_mnuRecibosRegistrarActionPerformed

    private void mnuProyectoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProyectoRegistrarActionPerformed
        
        frmProyectoInsert inser = new frmProyectoInsert();
        inser.setVisible(true);
        inser.setLocationRelativeTo(null);

    }//GEN-LAST:event_mnuProyectoRegistrarActionPerformed

    private void mnuProyectoUpDeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProyectoUpDeleActionPerformed
        
        frmProyectoUpDele updele = new frmProyectoUpDele();
        updele.setVisible(true);
        updele.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_mnuProyectoUpDeleActionPerformed

    private void mnuPersonalGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPersonalGestionActionPerformed
        
        frmPersonal personal = new frmPersonal();
        personal.setVisible(true);
        personal.setLocationRelativeTo(null);
                
    }//GEN-LAST:event_mnuPersonalGestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenu mnuPersonal;
    private javax.swing.JMenuItem mnuPersonalGestion;
    private javax.swing.JMenuItem mnuProyectoRegistrar;
    private javax.swing.JMenuItem mnuProyectoUpDele;
    private javax.swing.JMenu mnuProyectos;
    private javax.swing.JMenu mnuRecibos;
    private javax.swing.JMenuItem mnuRecibosRegistrar;
    private javax.swing.JMenu mnuSalir;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
