/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Victor Pino
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHerramientas = new javax.swing.JMenu();
        mnuHerramientasAddProyecto = new javax.swing.JMenuItem();
        mnuHerramientasUpdateProyecto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuHerramientaEmpleado = new javax.swing.JMenuItem();
        mnuHerramientasUpdateEmpleado = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuHerramientasAddProveedor = new javax.swing.JMenuItem();
        mnuHerramientasUpdateProveedor = new javax.swing.JMenuItem();
        mnuPersonal = new javax.swing.JMenu();
        mnuRecibos = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja Chica");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        mnuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/herra3-48.png"))); // NOI18N
        mnuHerramientas.setText("Herramientas Administrativas");

        mnuHerramientasAddProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proyecto-32.png"))); // NOI18N
        mnuHerramientasAddProyecto.setText("Registrar Proyecto");
        mnuHerramientasAddProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHerramientasAddProyectoActionPerformed(evt);
            }
        });
        mnuHerramientas.add(mnuHerramientasAddProyecto);

        mnuHerramientasUpdateProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/uppro-32.png"))); // NOI18N
        mnuHerramientasUpdateProyecto.setText("Modificar y/o Eliminar Proyecto");
        mnuHerramientasUpdateProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHerramientasUpdateProyectoActionPerformed(evt);
            }
        });
        mnuHerramientas.add(mnuHerramientasUpdateProyecto);
        mnuHerramientas.add(jSeparator1);

        mnuHerramientaEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios-32.png"))); // NOI18N
        mnuHerramientaEmpleado.setText("Registrar Empleado");
        mnuHerramientaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHerramientaEmpleadoActionPerformed(evt);
            }
        });
        mnuHerramientas.add(mnuHerramientaEmpleado);

        mnuHerramientasUpdateEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar-em-32.png"))); // NOI18N
        mnuHerramientasUpdateEmpleado.setText("Modificar y/o Eliminar Empleado");
        mnuHerramientasUpdateEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHerramientasUpdateEmpleadoActionPerformed(evt);
            }
        });
        mnuHerramientas.add(mnuHerramientasUpdateEmpleado);
        mnuHerramientas.add(jSeparator2);

        mnuHerramientasAddProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedor-32.png"))); // NOI18N
        mnuHerramientasAddProveedor.setText("Registrar Proveedor");
        mnuHerramientasAddProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHerramientasAddProveedorActionPerformed(evt);
            }
        });
        mnuHerramientas.add(mnuHerramientasAddProveedor);

        mnuHerramientasUpdateProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar-up-32.png"))); // NOI18N
        mnuHerramientasUpdateProveedor.setText("Modificar y/o Eliminar Proveedor");
        mnuHerramientasUpdateProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHerramientasUpdateProveedorActionPerformed(evt);
            }
        });
        mnuHerramientas.add(mnuHerramientasUpdateProveedor);

        jMenuBar1.add(mnuHerramientas);

        mnuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura-48.png"))); // NOI18N
        mnuPersonal.setText("Cargar Factura");
        jMenuBar1.add(mnuPersonal);

        mnuRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consultas-48.png"))); // NOI18N
        mnuRecibos.setText("Consultas");
        jMenuBar1.add(mnuRecibos);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuHerramientasAddProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHerramientasAddProyectoActionPerformed

        frmProyectoInsert inser = new frmProyectoInsert();
        inser.setVisible(true);
        inser.setLocationRelativeTo(null);

    }//GEN-LAST:event_mnuHerramientasAddProyectoActionPerformed

    private void mnuHerramientasUpdateProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHerramientasUpdateProyectoActionPerformed

        frmProyectoUpDele updele = new frmProyectoUpDele();
        updele.setVisible(true);
        updele.setLocationRelativeTo(null);


    }//GEN-LAST:event_mnuHerramientasUpdateProyectoActionPerformed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void mnuHerramientaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHerramientaEmpleadoActionPerformed

        frmPersonal personal = new frmPersonal();
        personal.setVisible(true);
        personal.setLocationRelativeTo(null);

    }//GEN-LAST:event_mnuHerramientaEmpleadoActionPerformed

    private void mnuHerramientasUpdateEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHerramientasUpdateEmpleadoActionPerformed

        frmPersonalUpdate up = new frmPersonalUpdate();
        up.setVisible(true);
        up.setLocationRelativeTo(null);

    }//GEN-LAST:event_mnuHerramientasUpdateEmpleadoActionPerformed

    private void mnuHerramientasAddProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHerramientasAddProveedorActionPerformed

        frmProveedor proveedor = new frmProveedor();
        proveedor.setVisible(true);
        proveedor.setLocationRelativeTo(null);

    }//GEN-LAST:event_mnuHerramientasAddProveedorActionPerformed

    private void mnuHerramientasUpdateProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHerramientasUpdateProveedorActionPerformed

        frmProveedorlUpdate up = new frmProveedorlUpdate();
        up.setVisible(true);
        up.setLocationRelativeTo(null);

    }//GEN-LAST:event_mnuHerramientasUpdateProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuHerramientaEmpleado;
    private javax.swing.JMenu mnuHerramientas;
    private javax.swing.JMenuItem mnuHerramientasAddProveedor;
    private javax.swing.JMenuItem mnuHerramientasAddProyecto;
    private javax.swing.JMenuItem mnuHerramientasUpdateEmpleado;
    private javax.swing.JMenuItem mnuHerramientasUpdateProveedor;
    private javax.swing.JMenuItem mnuHerramientasUpdateProyecto;
    private javax.swing.JMenu mnuPersonal;
    private javax.swing.JMenu mnuRecibos;
    private javax.swing.JMenu mnuSalir;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
