/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Datos;
import Clases.Opcion;
import Clases.Personal;
import Clases.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor Pino
 */
public class frmPersonal extends javax.swing.JFrame {

    /**
     * Creates new form frmPersonal
     */
    public frmPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        PanelTop = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        PersonalUsuario = new org.edisoncor.gui.panel.Panel();
        btnCancelarUsuario = new org.edisoncor.gui.button.ButtonAction();
        txtCorreoUsu = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        labelMetric8 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric9 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric10 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric12 = new org.edisoncor.gui.label.LabelMetric();
        btnSiguiente = new org.edisoncor.gui.button.ButtonAction();
        txtIdUsuario = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        labelMetric15 = new org.edisoncor.gui.label.LabelMetric();
        cmbTipo = new org.edisoncor.gui.comboBox.ComboBoxRound();
        txtClave = new org.edisoncor.gui.passwordField.PasswordFieldRoundIcon();
        txtConfirmarClave = new org.edisoncor.gui.passwordField.PasswordFieldRoundIcon();
        txtUsuario = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        labelMetric21 = new org.edisoncor.gui.label.LabelMetric();
        PersonalGerente = new org.edisoncor.gui.panel.Panel();
        labelMetric11 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric13 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric14 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric16 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric17 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric19 = new org.edisoncor.gui.label.LabelMetric();
        txtCedulaGerente = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtTelGe = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtCargoGe = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        btnRegistrarGe = new org.edisoncor.gui.button.ButtonAction();
        btnCancelarGe = new org.edisoncor.gui.button.ButtonAction();
        txtIDGerente = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtNomGe = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtApeGe = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        labelMetric20 = new org.edisoncor.gui.label.LabelMetric();
        cmbProyecto = new org.edisoncor.gui.comboBox.ComboBoxRound();
        PersonalEmpleado = new org.edisoncor.gui.panel.Panel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric5 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        txtCedulaEmpleado = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtTelEm = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtCargoEm = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        btnRegistrarEm = new org.edisoncor.gui.button.ButtonAction();
        btnCancelarEm = new org.edisoncor.gui.button.ButtonAction();
        txtIDEmpleado = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtNomEm = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtApeEm = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        labelMetric22 = new org.edisoncor.gui.label.LabelMetric();
        cmbGerente = new org.edisoncor.gui.comboBox.ComboBoxRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnCancelarUsuario.setText("Cancelar");
        btnCancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUsuarioActionPerformed(evt);
            }
        });

        labelMetric8.setText("Clave:");

        labelMetric9.setText("Confirmar Clave:");

        labelMetric10.setText("ID:");

        labelMetric12.setText("Correo:");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        labelMetric15.setText("Tipo:");

        labelMetric21.setText("Usuario:");

        javax.swing.GroupLayout PersonalUsuarioLayout = new javax.swing.GroupLayout(PersonalUsuario);
        PersonalUsuario.setLayout(PersonalUsuarioLayout);
        PersonalUsuarioLayout.setHorizontalGroup(
            PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
            .addGroup(PersonalUsuarioLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCorreoUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtConfirmarClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        PersonalUsuarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbTipo, txtClave, txtConfirmarClave, txtCorreoUsu, txtIdUsuario, txtUsuario});

        PersonalUsuarioLayout.setVerticalGroup(
            PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalUsuarioLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmarClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(PersonalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );

        PersonalUsuarioLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbTipo, txtClave, txtConfirmarClave, txtCorreoUsu, txtIdUsuario, txtUsuario});

        PanelTop.addTab("Usuario", PersonalUsuario);

        labelMetric11.setText("ID:");

        labelMetric13.setText("Cédula:");

        labelMetric14.setText("Nombre:");

        labelMetric16.setText("Apellido:");

        labelMetric17.setText("Telefono:");

        labelMetric19.setText("Cargo:");

        btnRegistrarGe.setText("Registrar");
        btnRegistrarGe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarGeActionPerformed(evt);
            }
        });

        btnCancelarGe.setText("Cancelar");
        btnCancelarGe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGeActionPerformed(evt);
            }
        });

        txtIDGerente.setEnabled(false);

        labelMetric20.setText("Proyecto:");

        javax.swing.GroupLayout PersonalGerenteLayout = new javax.swing.GroupLayout(PersonalGerente);
        PersonalGerente.setLayout(PersonalGerenteLayout);
        PersonalGerenteLayout.setHorizontalGroup(
            PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalGerenteLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalGerenteLayout.createSequentialGroup()
                        .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCargoGe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCedulaGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelGe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIDGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNomGe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApeGe, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(cmbProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PersonalGerenteLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnRegistrarGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(231, 231, 231))
        );
        PersonalGerenteLayout.setVerticalGroup(
            PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalGerenteLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApeGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargoGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(PersonalGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        PanelTop.addTab("Gerente", PersonalGerente);

        labelMetric1.setText("ID:");

        labelMetric2.setText("Cédula:");

        labelMetric3.setText("Nombre:");

        labelMetric4.setText("Apellido:");

        labelMetric5.setText("Telefono:");

        labelMetric7.setText("Cargo:");

        btnRegistrarEm.setText("Registrar");
        btnRegistrarEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmActionPerformed(evt);
            }
        });

        btnCancelarEm.setText("Cancelar");
        btnCancelarEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEmActionPerformed(evt);
            }
        });

        txtIDEmpleado.setEnabled(false);

        labelMetric22.setText("Gerente:");

        javax.swing.GroupLayout PersonalEmpleadoLayout = new javax.swing.GroupLayout(PersonalEmpleado);
        PersonalEmpleado.setLayout(PersonalEmpleadoLayout);
        PersonalEmpleadoLayout.setHorizontalGroup(
            PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalEmpleadoLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btnRegistrarEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PersonalEmpleadoLayout.createSequentialGroup()
                        .addComponent(labelMetric22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PersonalEmpleadoLayout.createSequentialGroup()
                        .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCargoEm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtTelEm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIDEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtNomEm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApeEm, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(222, 222, 222))
        );

        PersonalEmpleadoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCargoEm, txtCedulaEmpleado, txtIDEmpleado, txtTelEm});

        PersonalEmpleadoLayout.setVerticalGroup(
            PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalEmpleadoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApeEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargoEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(PersonalEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PersonalEmpleadoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCargoEm, txtCedulaEmpleado, txtIDEmpleado, txtTelEm});

        PanelTop.addTab("Empleado", PersonalEmpleado);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmActionPerformed
        /* Evento de click sobre el boton de REGISTRAR EMPLEADO */

        /* Instanciamos un objeto de la Clase Datos */
        Datos datos = new Datos();

        /* Validaciones */
        if (txtIDEmpleado.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el ID del Empleado");
            txtIDEmpleado.requestFocusInWindow();
            return;
        }

        if (txtCedulaEmpleado.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar una cedula");
            txtCedulaEmpleado.requestFocusInWindow();
            return;
        }

        if (txtNomEm.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un nombre ");
            txtNomEm.requestFocusInWindow();
            return;
        }

        if (txtApeEm.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un apellido ");
            txtApeEm.requestFocusInWindow();
            return;
        }

        if (txtTelEm.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe especificar un telefono de contacto ");
            txtTelEm.requestFocusInWindow();
            return;
        }

        if (txtCargoEm.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe especificar el cargo ");
            txtCargoEm.requestFocusInWindow();
            return;
        }

        if (cmbGerente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar el gerente");
            cmbGerente.requestFocusInWindow();
            return;
        }

        String clave = new String(txtClave.getPassword());

        /* Instanciamos un objeto de la Clase Usuario, el cual se lo pasaremos
         a la funcion agregarUsuario, la cual pide como parametro un objeto Usuario */
        Usuario usuario = new Usuario(Integer.parseInt(txtIdUsuario.getText()),
                cmbTipo.getSelectedIndex(),
                txtUsuario.getText(),
                clave,
                txtCorreoUsu.getText());

        int tele = Integer.parseInt(txtTelEm.getText());

        /* Instanciamos un objeto de la Clase Personal, el cual se lo pasaremos
         a la funcion agregarPersonal, la cual pide como parametro un objeto Personal */
        Personal personal = new Personal(Integer.parseInt(txtIDEmpleado.getText()),
                txtUsuario.getText(),
                txtCedulaEmpleado.getText(),
                txtNomEm.getText(),
                txtApeEm.getText(),
                tele,
                txtCargoEm.getText());

        /* Una ves instanciado y cargado el objeto llamamos a la funcion 
         agregarPersonal, validamos si la funcion retorna true, imprimimos en 
         pantalla un mensaje de aprobacion, si no lo contrario. */
        /*Id del empleado lo convertimos a integer para pasarselo a la funcion
         agregarEmGeren*/
        int idEm = Integer.parseInt(txtIDEmpleado.getText());

        /* Convertimos el Objeto que nos devuelve el combox a integer para pasarselo 
         a la funcion agregarEmGeren */
        int idGeren = Integer.parseInt(((Opcion) cmbGerente.getSelectedItem()).getValor());

        if (datos.agregarUsuario(usuario) && datos.agregarPersonal(personal)
                && datos.agregarEmGeren(idEm, idGeren)) {
            JOptionPane.showMessageDialog(this, "Empleado Agregado Correctamente");

        } else {
            JOptionPane.showMessageDialog(this, "En estos momentos no es posible"
                    + " agregar al Empleado, intentelo mas tarde");
        }
        
          /* Limpiamos lo campos  */
        txtUsuario.setText("");
        txtCedulaGerente.setText("");
        txtNomGe.setText("");
        txtApeGe.setText("");
        txtTelGe.setText("");
        txtCargoGe.setText("");
        
        setVisible(false);

    }//GEN-LAST:event_btnRegistrarEmActionPerformed

    private void btnCancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUsuarioActionPerformed

        setVisible(false);

    }//GEN-LAST:event_btnCancelarUsuarioActionPerformed

    private void btnRegistrarGeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarGeActionPerformed
        /* Evento de click sobre el boton de REGISTRAR Gerente */

        /* Instanciamos un objeto de la Clase Datos */
        Datos datos = new Datos();

        /* Validaciones */
        if (txtIDGerente.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el ID del Gerente");
            txtIDGerente.requestFocusInWindow();
            return;
        }

        if (txtCedulaGerente.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar una cedula");
            txtCedulaGerente.requestFocusInWindow();
            return;
        }

        if (txtNomGe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un nombre ");
            txtNomGe.requestFocusInWindow();
            return;
        }

        if (txtApeGe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un apellido ");
            txtApeGe.requestFocusInWindow();
            return;
        }

        if (txtTelGe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe especificar un telefono de contacto ");
            txtTelGe.requestFocusInWindow();
            return;
        }

        if (txtCargoGe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe especificar el cargo ");
            txtCargoGe.requestFocusInWindow();
            return;
        }

        if (cmbProyecto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar un Proyecto");
            cmbProyecto.requestFocusInWindow();
            return;
        }

        String clave = new String(txtClave.getPassword());

        /* Instanciamos un objeto de la Clase Usuario, el cual se lo pasaremos
         a la funcion agregarUsuario, la cual pide como parametro un objeto Usuario */
        Usuario usuario = new Usuario(Integer.parseInt(txtIdUsuario.getText()),
                cmbTipo.getSelectedIndex(),
                txtUsuario.getText(),
                clave,
                txtCorreoUsu.getText());

        /* Instanciamos un objeto de la Clase Personal, el cual se lo pasaremos
         a la funcion agregarPersonal, la cual pide como parametro un objeto Personal */
        Personal personal = new Personal(Integer.parseInt(txtIDGerente.getText()),
                txtUsuario.getText(),
                txtCedulaGerente.getText(),
                txtNomGe.getText(),
                txtApeGe.getText(),
                Integer.parseInt(txtTelGe.getText()),
                txtCargoGe.getText());

        /* Una ves instanciado y cargado el objeto llamamos a la funcion 
         agregarPersonal, validamos si la funcion retorna true, imprimimos en 
         pantalla un mensaje de aprobacion, si no lo contrario. */
        /*Id del gerente lo convertimos a integer para pasarselo a la funcion
         agregarProyeGere*/
        int idGere = Integer.parseInt(txtIDGerente.getText());

        /* Convertimos el Objeto que nos devuelve el combox a integer para 
         pasarselo a la funcion agregarProyeGere */
        int idPro = Integer.parseInt(((Opcion) cmbProyecto.getSelectedItem()).getValor());

        JOptionPane.showMessageDialog(this, " " + idPro);

        if (datos.agregarUsuario(usuario) && datos.agregarPersonal(personal)
                && datos.agregarProyeGere(idPro, idGere)) {
            JOptionPane.showMessageDialog(this, "Gerente Agregado Correctamente");

        } else {
            JOptionPane.showMessageDialog(this, "En estos momentos no es posible"
                    + " agregar al Gerente, intentelo mas tarde");
        }

        /* Limpiamos lo campos  */
        txtUsuario.setText("");
        txtCedulaGerente.setText("");
        txtNomGe.setText("");
        txtApeGe.setText("");
        txtTelGe.setText("");
        txtCargoGe.setText("");
        
        setVisible(false);

    }//GEN-LAST:event_btnRegistrarGeActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        /* Validaciones */
        if (txtIdUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el ID del usuario");
            txtIdUsuario.requestFocusInWindow();
            return;
        }

        if (cmbTipo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar un tipo de usuario");
            cmbTipo.requestFocusInWindow();
            return;
        }

        if (txtUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un nombre de usuario");
            txtUsuario.requestFocusInWindow();
            return;
        }

        /* Como el cambo passwordfield nos devuelve un array, hay que transformarlo 
         a String para validarlo y luego compararlo con la confirmacion */
        String clave = new String(txtClave.getPassword());

        if (clave.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar la clave del usuario");
            txtClave.requestFocusInWindow();
            return;
        }

        String confirmar = new String(txtConfirmarClave.getPassword());

        if (confirmar.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe confirmar la clave ");
            txtConfirmarClave.requestFocusInWindow();
            return;
        }

        if (!clave.equals(confirmar)) {
            JOptionPane.showMessageDialog(rootPane, "Las claves no coinciden, "
                    + "por favor vuelva a ingresarlas");
            txtClave.setText("");
            txtConfirmarClave.setText("");
            txtClave.requestFocusInWindow();
            return;
        }

        if (txtCorreoUsu.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un correo ");
            txtCorreoUsu.requestFocusInWindow();
            return;
        }

        /* Una ves todo validado pasamos al formulario siguiente dependiendo
         del tipo de usuario que hallan seleccionado. */
        if (((Opcion) cmbTipo.getSelectedItem()).getValor().equals("1")) {

            /* Si el tipo seleccionado es igual a 1, Mostramos el formulario
             de gerente */
            PanelTop.setSelectedComponent(PersonalGerente);

        }

        if (((Opcion) cmbTipo.getSelectedItem()).getValor().equals("2")) {

            /* Si el tipo seleccionado es igual a 2, Mostramos el formulario
             de gerente */
            PanelTop.setSelectedComponent(PersonalEmpleado);

        }

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            /* Evento cuando el formulario se abra */

            /* Instanciamos un objeto de la Clase Datos, para poder acceder a los
             metodos */
            Datos datos = new Datos();

            /* Cargamos los ID en los formularios */
            int idUsu = datos.getIdUsuario();
            txtIdUsuario.setText("" + idUsu);

            int idPer = datos.getIdPersonal();
            txtIDGerente.setText("" + idPer);
            txtIDEmpleado.setText("" + idPer);

            /* Instaciamos un objeto de la clase Opcion para cargar el combo box 
             de tipos de usuarios  */
            Opcion op = new Opcion("0", "Seleccione el tipo de usuario");

            /* Añadimos el primer elemento al combo box */
            cmbTipo.addItem(op);

            /* Llamos a la funcion getTipoUsuario la cual nos devuelve todos los tipos
             de usuarios que hay, esos datos los guardmoas en un ResultSet para luego
             llenar el combo box con todos los tipos de usuarios */
            ResultSet rs = datos.getTiposUsuario();

            /* Hacemos un while que mientras hallan registros en rs, sobreescrira
             al objeto de la clase opcion con los datos del objeto rs, y los añada
             al combo box */
            while (rs.next()) {
                op = new Opcion(
                        rs.getString("id_tipo"),
                        rs.getString("nom_tipo"));
                cmbTipo.addItem(op);
            }

            /* Instaciamos un objeto de la clase Opcion para cargar el combo box 
             de proyectos  */
            Opcion op2 = new Opcion("0", "Seleccione un proyecto");

            /* Añadimos el primer elemento al combo box */
            cmbProyecto.addItem(op2);

            /* Llamos a la funcion getProyectos la cual nos devuelve todos los 
             proyectos que hay, esos datos los guardmoas en un ResultSet para luego
             llenar el combo box con todos los proyectos */
            ResultSet rsPro = datos.getProyectos();

            /* Hacemos un while que mientras hallan registros en rs, sobreescrira
             al objeto de la clase opcion con los datos del objeto rs, y los añada
             al combo box */
            while (rsPro.next()) {
                op2 = new Opcion(
                        rsPro.getString("id_proyecto"),
                        rsPro.getString("nom_pro"));
                cmbProyecto.addItem(op2);
            }

            /* Instaciamos un objeto de la clase Opcion para cargar el combo box 
             de gerentes  */
            Opcion op3 = new Opcion("0", "Seleccione un gerente");

            /* Añadimos el primer elemento al combo box */
            cmbGerente.addItem(op3);

            /* Llamos a la funcion getGerentes la cual nos devuelve todos los 
             gerentes que hay, esos datos los guardamos en un ResultSet para luego
             llenar el combo box con todos los gerentes */
            ResultSet rsGere = datos.getGerentes();

            /* Hacemos un while que mientras hallan registros en rs, sobreescrira
             al objeto de la clase opcion con los datos del objeto rs, y los añada
             al combo box */
            while (rsGere.next()) {
                op3 = new Opcion(
                        rsGere.getString("id_personal"),
                        rsGere.getString("nom_per")
                        + " " + rsGere.getString("ape_per"));
                cmbGerente.addItem(op3);
            }

        } catch (SQLException ex) {
            Logger.getLogger(frmPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEmActionPerformed

        setVisible(false);

    }//GEN-LAST:event_btnCancelarEmActionPerformed

    private void btnCancelarGeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGeActionPerformed
        setVisible(false);

    }//GEN-LAST:event_btnCancelarGeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader PanelTop;
    private org.edisoncor.gui.panel.Panel PersonalEmpleado;
    private org.edisoncor.gui.panel.Panel PersonalGerente;
    private org.edisoncor.gui.panel.Panel PersonalUsuario;
    private org.edisoncor.gui.button.ButtonAction btnCancelarEm;
    private org.edisoncor.gui.button.ButtonAction btnCancelarGe;
    private org.edisoncor.gui.button.ButtonAction btnCancelarUsuario;
    private org.edisoncor.gui.button.ButtonAction btnRegistrarEm;
    private org.edisoncor.gui.button.ButtonAction btnRegistrarGe;
    private org.edisoncor.gui.button.ButtonAction btnSiguiente;
    private org.edisoncor.gui.comboBox.ComboBoxRound cmbGerente;
    private org.edisoncor.gui.comboBox.ComboBoxRound cmbProyecto;
    private org.edisoncor.gui.comboBox.ComboBoxRound cmbTipo;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric10;
    private org.edisoncor.gui.label.LabelMetric labelMetric11;
    private org.edisoncor.gui.label.LabelMetric labelMetric12;
    private org.edisoncor.gui.label.LabelMetric labelMetric13;
    private org.edisoncor.gui.label.LabelMetric labelMetric14;
    private org.edisoncor.gui.label.LabelMetric labelMetric15;
    private org.edisoncor.gui.label.LabelMetric labelMetric16;
    private org.edisoncor.gui.label.LabelMetric labelMetric17;
    private org.edisoncor.gui.label.LabelMetric labelMetric19;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric20;
    private org.edisoncor.gui.label.LabelMetric labelMetric21;
    private org.edisoncor.gui.label.LabelMetric labelMetric22;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.label.LabelMetric labelMetric5;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private org.edisoncor.gui.label.LabelMetric labelMetric8;
    private org.edisoncor.gui.label.LabelMetric labelMetric9;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtApeEm;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtApeGe;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtCargoEm;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtCargoGe;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtCedulaEmpleado;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtCedulaGerente;
    private org.edisoncor.gui.passwordField.PasswordFieldRoundIcon txtClave;
    private org.edisoncor.gui.passwordField.PasswordFieldRoundIcon txtConfirmarClave;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtCorreoUsu;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtIDEmpleado;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtIDGerente;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtIdUsuario;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtNomEm;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtNomGe;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtTelEm;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtTelGe;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtUsuario;
    // End of variables declaration//GEN-END:variables
}
